name: SetUp-EC2-Vault
on:
  push:
    branches:
      - Infra
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“¦Checkout code
      uses: actions/checkout@v4

    - name: âš™ï¸Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: ğŸ”¨Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5  

    - name: âœ…Terraform Init
      run: terraform init
      working-directory: .

    - name: âœ…Terraform Validate
      run: terraform validate
      working-directory: .

    - name: ğŸ“‹Terraform Plan
      run: terraform plan
      working-directory: .

    - name: ğŸš€Terraform Apply (auto-approve)
      run: terraform apply -auto-approve
      working-directory: .
